<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Sahar Jiwani" />
    <meta name="description" content="This is my site">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Statistical Modeling</title>
    <meta name="generator" content="Hugo 0.60.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="Resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Statistical Modeling</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          December 11, 2019
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p>The researchers of this dataset were testing the IQ levels of post-comatose patients. The first variable, id, is patient’s ID number. The second variable, days, is the number of days after awaking from the coma that IQ was measured. The third variable, duration, is how many days the coma lasted. The fourth variable, sex, identifies if the patient is male or female. The fifth variable, age, is age at the time of injury. The sixth variable, piq, is performance IQ score while the seventh variable, viq, is the verbal IQ score.</p>
<p>#Task 1: MANOVA</p>
<pre class="r"><code>Wong&lt;-read.csv(&quot;Wong.csv&quot;)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(ggplot2)
coma &lt;- Wong
man1&lt;-manova(cbind(age,duration, days, piq, viq)~sex, data=coma)
summary(man1)</code></pre>
<pre><code>##            Df   Pillai approx F num Df den Df Pr(&gt;F)
## sex         1 0.023766   1.5824      5    325 0.1645
## Residuals 329</code></pre>
<pre class="r"><code>#Type I error 
1-(.95)^6</code></pre>
<pre><code>## [1] 0.2649081</code></pre>
<pre class="r"><code>#Bonferroni
.05/6</code></pre>
<pre><code>## [1] 0.008333333</code></pre>
<p>The result of the MANOVA was not significant (p-value=0.1645) This means that for each response variable (age, duration, days, piq, viq), the means of the groups of the categorical variable (sex) are equal. If the MANOVA was significant, I would have performed 5 ANOVAs, one for each numeric variable, but no post-hoc tests because the response variable only has two levels. Including the MANOVA, this is 6 total tests. The probability of a Type I error 26.49% The value of Bonferroni’s correction is 0.0083333. There are many MANOVA assumptions. The ones that are likely to be met are independent sample and random observation and no extreme outliers. The rest of the assumptions are probably not met. No multicollinearity, for example, may not be likely as those who score highly on piq probably also score highly on viq. Multivariate normality is very hard to show and chances are this data set fails to meet this assumption claiming the residuals are normally distributed. The final assumption is that there is homogeneity of within-group covariance matrices, which is likely also not met.</p>
<p>#Task 2: Randomization Test</p>
<pre class="r"><code>#Two-sample t-test 
t.test(data=coma,piq~sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  piq by sex
## t = 0.89608, df = 95.285, p-value = 0.3725
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.517771  6.660891
## sample estimates:
## mean in group Female   mean in group Male 
##             89.18310             87.11154</code></pre>
<pre class="r"><code>t.test(data=coma, viq~sex)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  viq by sex
## t = -0.40953, df = 109.86, p-value = 0.6829
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.546722  2.989409
## sample estimates:
## mean in group Female   mean in group Male 
##             94.35211             95.13077</code></pre>
<pre class="r"><code>t&lt;-vector() 
for(i in 1:10000){
 samp&lt;-rnorm(25,mean=5) 
 t[i] &lt;- (mean(samp)-5)/(sd(samp)/sqrt(25)) 
}
data.frame(t)%&gt;%
ggplot(aes(t))+geom_histogram(aes(y=..density..), bins=30)+
 stat_function(fun=dt,args=list(df=24),geom=&quot;line&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>I wanted to test if the means across the IQ test scores were significantly different from the means of the levels of the sex variable. The null hypothesis for both tests is that there is no difference in the means between the IQ test scores and sex. The alternative hypothesis is that there is a difference in the means between the two variables. My first t-test, which looked at sex and viq, had a p-value of 0.6829. This means there is no significant difference in the means of the viq across the means of the two sexes. Therefore, males and females scored the same, on average, on the viq. The same is true for the second t-test in which I tested sex and piq. The p-value for this test was 0.3725, which is not significant. This means males and females scored the same, on average, on the piq.</p>
<p>#Task 3: Linear Regression</p>
<pre class="r"><code>library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>library(sandwich)
#piq, age, sex regression and plot
coma$piq_c&lt;-coma$piq-mean(coma$piq)
coma$age_c&lt;-coma$age-mean(coma$age)
fit&lt;-lm(piq_c~ age_c * sex, data=coma); summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = piq_c ~ age_c * sex, data = coma)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.855 -10.673  -0.570   9.711  44.597 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    1.708434   1.802880   0.948    0.344
## age_c          0.082199   0.148088   0.555    0.579
## sexMale       -2.172446   2.032842  -1.069    0.286
## age_c:sexMale -0.009343   0.162055  -0.058    0.954
## 
## Residual standard error: 15.14 on 327 degrees of freedom
## Multiple R-squared:  0.00782,    Adjusted R-squared:  -0.001282 
## F-statistic: 0.8591 on 3 and 327 DF,  p-value: 0.4626</code></pre>
<pre class="r"><code>ggplot(coma, aes(x=age, y=piq,group=sex))+geom_point(aes(color=sex))+
 geom_smooth(method=&quot;lm&quot;,formula=y~1,se=F,fullrange=T,aes(color=sex))+
theme(legend.position=c(.9,.19))+xlab(&quot;Age&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>#linearity, homoskedasticity 
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code>#normality 
ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-3.png" width="672" /></p>
<pre class="r"><code>#robust SE
coeftest(fit, vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                   Estimate Std. Error
## (Intercept)    1.708433691  2.1801491
## age_c          0.082199215  0.1963573
## sexMale       -2.172446471  2.3540817
## age_c:sexMale -0.009342535  0.2048703</code></pre>
<pre class="r"><code>#proportion of variation explained by model
summary(fit)$r.sq</code></pre>
<pre><code>## [1] 0.007820354</code></pre>
<p>The intercept explains the likely piq value when age and sex are 0. Since it is impossible for sex and to equal 0, this number does not provide any meaningful information. Age_c tells us if we were to hold sex constant, every 1 year increase in age would increase piq scores by .0822 points. SexMale tells us that controlling for age, being a male will decrease the piq score by 2.17 points compared to females. The interaction explains if the effect of sex on piq score differs by age. The graphs for linearity, normality, and homoskedasticity all look normal meaning all assumptions are met. When recomputing the regression with robust standard error via the coeftest function, all the standard errors increased compared to the regualar regression. The proportion of the variation explained by my model is 0.007820345.</p>
<p>#Task 4: Bootstrapping</p>
<pre class="r"><code>fit&lt;-lm(piq_c~ age_c * sex, data=coma); summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = piq_c ~ age_c * sex, data = coma)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.855 -10.673  -0.570   9.711  44.597 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    1.708434   1.802880   0.948    0.344
## age_c          0.082199   0.148088   0.555    0.579
## sexMale       -2.172446   2.032842  -1.069    0.286
## age_c:sexMale -0.009343   0.162055  -0.058    0.954
## 
## Residual standard error: 15.14 on 327 degrees of freedom
## Multiple R-squared:  0.00782,    Adjusted R-squared:  -0.001282 
## F-statistic: 0.8591 on 3 and 327 DF,  p-value: 0.4626</code></pre>
<pre class="r"><code>#boostrap residuals 
 resids&lt;-fit$residuals 
 fitted&lt;-fit$fitted.values 
 resid_resamp&lt;-replicate(5000,{
 new_resids&lt;-sample(resids,replace=TRUE) 
 coma$new_y&lt;-fitted+new_resids 
 fit1&lt;-lm(new_y~age_c+sex,data=coma) 
 coef(fit1) 
})
 resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)      age_c  sexMale
## 1    1.803454 0.05980609 2.023588</code></pre>
<p>The new bootstrapped standard error for age decreased substantially from both the orginal value and the robust SE value. The orginal SE was 0.148088, the robust standard error increased to 0.1963573, and the boostrapped standard error is only 0.060064.
The boostrapped standard error for sexMale was also less than the other standard errors. The original was 2.032842, the robust SE increased to 2.3540817 and the bootstrapped value is 2.00616</p>
<p>#Task 5:Logistic Regression</p>
<pre class="r"><code>#regression
fit2&lt;-glm(sex~age+duration+piq, family=&quot;binomial&quot;, data=coma)
coeftest(fit2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  1.2164005  0.8969086  1.3562  0.17503  
## age          0.0112687  0.0102808  1.0961  0.27304  
## duration     0.0177093  0.0099683  1.7766  0.07564 .
## piq         -0.0054446  0.0090179 -0.6038  0.54601  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit2))</code></pre>
<pre><code>## (Intercept)         age    duration         piq 
##   3.3750174   1.0113325   1.0178671   0.9945702</code></pre>
<pre class="r"><code>#confusion matrix
class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  

  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}
prob&lt;- predict(fit2, type = &quot;response&quot;)
class_diag(prob, coma$sex)</code></pre>
<pre><code>##            acc sens spec       ppv       auc
## Male 0.7854985    1    0 0.7854985 0.6048212</code></pre>
<pre class="r"><code>table(predict = as.numeric(prob&gt;0.5), truth = coma$sex)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict Female Male Sum
##     1       71  260 331
##     Sum     71  260 331</code></pre>
<pre class="r"><code>#ROC  
library(plotROC)
ROCplot&lt;-ggplot(coma)+geom_roc(aes(d=sex,m=prob), n.cuts=0) 
ROCplot</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming Female = 0 and Male =
## 1!</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>#AUC, Accuracy, TPR...
prob &lt;- predict(fit2, type = &quot;response&quot;)
class_diag &lt;- function(probs, truth) {
tab &lt;- table(factor(probs &gt; 0.5, levels = c(&quot;FALSE&quot;, &quot;TRUE&quot;)),
truth)
acc = sum(diag(tab))/sum(tab)
sens = tab[2, 2]/colSums(tab)[2]
spec = tab[1, 1]/colSums(tab)[1]
ppv = tab[2, 2]/rowSums(tab)[2]
if (is.numeric(truth) == FALSE &amp; is.logical(truth) == FALSE)
truth &lt;- as.numeric(truth) - 1
ord &lt;- order(probs, decreasing = TRUE)
probs &lt;- probs[ord]
truth &lt;- truth[ord]
TPR = cumsum(truth)/max(1, sum(truth))
FPR = cumsum(!truth)/max(1, sum(!truth))
dup &lt;- c(probs[-1] &gt;= probs[-length(probs)], FALSE)
TPR &lt;- c(0, TPR[!dup], 1)
1
FPR &lt;- c(0, FPR[!dup], 1)
n &lt;- length(TPR)
auc &lt;- sum(((TPR[-1] + TPR[-n])/2) * (FPR[-1] - FPR[-n]))
data.frame(acc, sens, spec, ppv, auc)
}
class_diag(prob,coma$sex)</code></pre>
<pre><code>##            acc sens spec       ppv       auc
## Male 0.7854985    1    0 0.7854985 0.6048212</code></pre>
<pre class="r"><code>#5-fold CV
set.seed(1234) 
k = 5
data1 &lt;- coma[sample(nrow(coma)), ]
folds &lt;- cut(seq(1:nrow(coma)), breaks = k, labels = F) 
diags &lt;- NULL
for (i in 1:k) {
 train &lt;- data1[folds != i, ]
 test &lt;- data1[folds == i, ]
 truth &lt;- test$sex
 fit4 &lt;- glm(sex ~ piq+ viq , data = coma, family = &quot;binomial&quot;) 
 probs &lt;- predict(fit4, newdata = test, type = &quot;response&quot;) 
 preds &lt;- ifelse(probs &gt; 0.5, 1, 0)
 diags &lt;- rbind(diags, class_diag(probs, truth)) 
}
diags %&gt;% summarize_all(mean)</code></pre>
<pre><code>##         acc sens spec       ppv       auc
## 1 0.7856626    1    0 0.7856626 0.5432467</code></pre>
<pre class="r"><code>#density plot
odds&lt;-function(p)p/(1-p)
p&lt;-seq(0,1,by=.1)
logit&lt;-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds   logit
##  [1,] 0.0 0.0000    -Inf
##  [2,] 0.1 0.1111 -2.1972
##  [3,] 0.2 0.2500 -1.3863
##  [4,] 0.3 0.4286 -0.8473
##  [5,] 0.4 0.6667 -0.4055
##  [6,] 0.5 1.0000  0.0000
##  [7,] 0.6 1.5000  0.4055
##  [8,] 0.7 2.3333  0.8473
##  [9,] 0.8 4.0000  1.3863
## [10,] 0.9 9.0000  2.1972
## [11,] 1.0    Inf     Inf</code></pre>
<pre class="r"><code>coma$logit&lt;-predict(fit2) 
coma$outcome&lt;-factor(coma$sex,levels=c(&quot;Female&quot;,&quot;Male&quot;))
ggplot(coma,aes(logit, fill=as.factor(sex)))+geom_density(alpha=.3)+
 geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<p>It is difficult to interpret these coefficients because it is unlikely that factors like age, duration, and piq can accurately predict if the patient is male or female. After exponentiation of coefficients, according to this regression, the coefficient estimate for age tells us that for every 1 year increase in age, the odds of being a female multiply by 1.01. For every 1 day increase in duration, odds of being a woman multiplies by 1.018, meaning females probably had longer durations than men by 1.018 days. For every 1 point increase in piq, the odds of being a female multiplies by 0.99, which means females had higher piq scores than males. Accuracy is 0.7854985, which is the porportion of correctly classified cases. Sensitivity is 1, meaning the true positive rate was 100% The confusion matrix did not predict “0” for anyone, meaning predicted probabilities were above 0.5. Specificity is 0, which is the true negative rate. PPV is 0.78549, which is the positive predicted value. AUC is 0.6048212, which is why the ROC graph is not a perfect curve.</p>
<p>#Task 6: LASSO</p>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loaded glmnet 3.0-1</code></pre>
<pre class="r"><code>library(dplyr)
data(coma)</code></pre>
<pre><code>## Warning in data(coma): data set &#39;coma&#39; not found</code></pre>
<pre class="r"><code>y&lt;-as.matrix(coma$piq)
x&lt;-coma%&gt;%dplyr::select(viq,duration,age, days)%&gt;%mutate_all(scale)%&gt;%as.matrix
cv&lt;-cv.glmnet(x,y) 
lasso1&lt;-glmnet(x,y,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 5 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                     s0
## (Intercept) 87.5558912
## viq          7.6278981
## duration    -0.3637986
## age          .        
## days         .</code></pre>
<pre class="r"><code>#CV
set.seed(1234)
k=10
data2&lt;-coma[sample(nrow(coma)),] 
folds&lt;-cut(seq(1:nrow(coma)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data2[folds!=i,]
 test&lt;-data2[folds==i,]
 fit5&lt;-lm(piq~viq+duration,data=train)
 yhat&lt;-predict(fit,newdata=test)
 diags&lt;-mean((test$piq-yhat)^2)
}
mean(diags)</code></pre>
<pre><code>## [1] 8188.596</code></pre>
<pre class="r"><code>summary(fit5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = piq ~ viq + duration, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.718  -6.215  -0.885   7.196  33.884 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.42964    4.58021   5.334 1.92e-07 ***
## viq          0.67979    0.04781  14.218  &lt; 2e-16 ***
## duration    -0.09629    0.02479  -3.884 0.000127 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.45 on 295 degrees of freedom
## Multiple R-squared:  0.4209, Adjusted R-squared:  0.417 
## F-statistic: 107.2 on 2 and 295 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The variables retained after conducting the lasso regression is viq and duration. For the regression, I did not include categorial variables or variables that did not make sense to include such as the mean centered variables in the dataset. The residual standard error was 11.42, which is much smaller than the standard error from the 5-fold CV, which was 7253.34.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
